version: "1"
rules:
  - base: master
    upstream: tensor-compiler:master
    mergeMethod: none  # Don't automatically merge it
  - base: llvm-backend
    upstream: tensor-compiler:master
    mergeMethod: none
    reviewers:              # Optional
      - guilhermeleobas
      - hameerabbasi
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict