name: "CUDA build and test (on push)"

# Note: NOT triggered by pull requests.  Pull requests should be reviewed
# by a human first, then triggered manually.  See cuda-test-manual.yml.
on:
  push:
    branches:
      - master
jobs:
  ubuntu1604-cuda:
    name: tests ubuntu 16.04 with CUDA 9
    runs-on: [self-hosted, ubuntu-16.04, cuda]
    steps:
    - uses: actions/checkout@v2
    - name: create_build
      run: mkdir build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DCUDA=ON -DOPENMP=ON -DPYTHON=OFF ..
      working-directory: build
    - name: make
      run: make -j8
      working-directory: build
    - name: test
      run: make test
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
        CTEST_PARALLEL_LEVEL: 8
      working-directory: build
